// Code generated by Codex from user prompt
let lastScrollY = window.scrollY;
let ticking = false;
const header = document.getElementById('main-header');

function onScroll() {
  const currentScrollY = window.scrollY;
  if (currentScrollY > lastScrollY && currentScrollY > header.offsetHeight) {
    header.classList.remove('show-header');
    header.classList.add('hide-header');
  } else {
    header.classList.remove('hide-header');
    header.classList.add('show-header');
  }
  lastScrollY = currentScrollY;
  ticking = false;
}

window.addEventListener('scroll', () => {
  if (!ticking) {
    window.requestAnimationFrame(onScroll);
    ticking = true;
  }
});
